#!/bin/zsh -x

# https://stackoverflow.com/questions/16860877/remove-an-element-from-a-bash-array
# Array names cannot start with RFA_
remove_from_array() {
    RFA_RETURN=()
    local RFA_ARRAY=$1
    local RFA_TO_REMOVE=$2
    for mem in "${(P)${RFA_ARRAY}[@]}"; do
        for remove in "${(P)${RFA_TO_REMOVE}[@]}"; do
            local KEEP=true
            if [[ "${mem}" == "${remove}" ]]; then
                local KEEP=false
                break
            fi
        done
        if ${KEEP}; then
            RFA_RETURN+=(${mem})
        fi
    done
}

array_contains_element () {
    local e match="$1"
    shift
    for e; do [[ "$e" == "$match" ]] && return 0; done
    return 1
}
