#!/bin/zsh

# This is kept in a separate file so it is easily modifable
BUILTIN_PACKAGES_DIR="${SCRIPTS_DIR}/builtin_packages"

populate_builtins() {
    if [[ "${#PACKAGES[@]}" == "0" ]]; then
        PACKAGES=(
            "${BUILTIN_PACKAGES_DIR}/xorgproto-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/lib32-tk-gentz"
            "${BUILTIN_PACKAGES_DIR}/lib32-mpdecimal-gentz"
            "${BUILTIN_PACKAGES_DIR}/python2-gentz"
            "${BUILTIN_PACKAGES_DIR}/python-gentz"

            "${BUILTIN_PACKAGES_DIR}/libx11-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/lib32-libedit-gentz"
            "${BUILTIN_PACKAGES_DIR}/llvm-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/openmpi-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/valgrind-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/lib32-libomxil-bellagio-gentz"
            "${BUILTIN_PACKAGES_DIR}/libdrm-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/mesa-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/xorg-server-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/xf86-video-amdgpu-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/xf86-video-ati-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/xf86-video-fbdev-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/xf86-video-vesa-git-gentz"

            "${BUILTIN_PACKAGES_DIR}/wine-staging-git-gentz"
            "${BUILTIN_PACKAGES_DIR}/winetricks-git"
        )

        print_fallback_param "PACKAGES" "${PACKAGES[@]}"
    fi
}
