#!/bin/zsh -x

if [[ "$1" != "32" && "$1" != "64" ]]; then
    echo "\"$1\" must be 32/64."
    exit 1
fi

local PKG_ROOT=""
[[ "$1" == "32" ]] && PKG_ROOT="lib32-"

if [[ "$(pacman -Q "$PKG_ROOT"llvm-git-gentz | wc -l)" != "1" ]]; then
    echo "Missing gentz package."
else
    sudo rm -f "/opt/llvm$1-sym"
    sudo ln -sf "$2" "/opt/llvm$1-sym"
fi
