.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GABS\-BUILD\-CONFIG" "5" "November 2019" "" ""
.
.SH "NAME"
\fBgabs\-build\-config\fR \- \fBgabs\-build\fR configuration script
.
.SH "DESCRIPTION"
\fBgabs\-build\-config\fR is a small script that should set the \fB${BUILTINS_DIR}\fR env variable and the list of builtin packages\. This script is sourced in by \fBgabs\-build\-handler\fR and \fBgabs\-build\fR and can be overridden by their \fB\-bcs\fR option, see gabs\-build(1) and gabs\-build\-handler(1)\.
.
.SH "AUTHOR"
Freya Gentz <zegentzy@protonmail\.com>
.
.SH "SEE ALSO"
gabs\-build(1), gabs\-build\-handler(1)
