.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GABS\-BUILD\-CHROOT" "1" "November 2019" "" ""
.
.SH "NAME"
\fBgabs\-build\-chroot\fR \- manages the creation of chroots in loopback devices backed by files
.
.SH "SYNOPSIS"
\fBgabs\-build\-chroot\fR [OPTIONS\.\.\.]
.
.SH "DESCRIPTION"
\fBgabs\-build\-chroot\fR is a small script in use by \fBgabs\-build\fR to manage chroots\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR:
.
.IP
Cleanup the specified chroot, unmounting all directories using the loopback devices using this file, then removing those loopback devices\. Processed before \fB\-s\fR\.
.
.TP
\fB\-s\fR:
.
.IP
Opens a loopback device using this file, then mounts it at the specified directory\.
.
.TP
\fB\-rm\fR:
.
.IP
(Re)make the file, deleting the old one if it exists\. For use in\-tangent with \fB\-s\fR, otherwise no\-op\.
.
.TP
\fB\-lds <SIZE>\fR:
.
.IP
Passed to \fBfallocate\fR directly as \fB\-l <SIZE>\fR\. See fallocate(1)\. Defaults to 50G\. For use in\-tangent with \fB\-rm\fR, otherwise no\-op\.
.
.TP
\fB\-cn <CHROOT_NAME>\fR:
.
.IP
Chroot name\. Defaults to "chroot"\. For use with \fB\-ed\fR\. If \fB\-cn\fR is present, \fB\-cm\fR and \fB\-cf\fR are auto\-calculated\. Please refer to \fB\-cn\fR in gabs\-build(1) for more details\.
.
.TP
\fB\-ed <EPHEMERAL_DIR>\fR:
.
.IP
Ephemeral dir\. For use with \fB\-ed\fR\. If present, \fB\-cm\fR and \fB\-cf\fR are auto\-calculated\. Please refer to \fB\-ed\fR in gabs\-build(1) for more details\.
.
.TP
\fB\-cm <CHROOT_MOUNT>\fR:
.
.IP
Where to mount the chroot\. Can be auto\-calculated if \fB\-ed\fR is passed in\.
.
.TP
\fB\-cf <CHROOT_FILE>\fR:
.
.IP
Which file to mount/create\. Can be auto\-calculated if \fB\-ed\fR is passed in,
.
.SH "AUTHOR"
Freya Gentz <zegentzy@protonmail\.com>
.
.SH "SEE ALSO"
gabs\-build(1)
